[package]
name = "oneshot-mpv"
description = "Safe, dynamically-loaded bindings to the libmpv client API"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
libloading.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
