// Publishes a Flick release on GitHub, where installed copies look for
// updates (tauri.conf.json › plugins.updater).
//
//   pnpm release            build this platform, sign, upload to the draft release v<version>
//   pnpm release:publish    publish the draft: installed copies are offered it
//
// Run `pnpm release` on Windows and on macOS (same commit, same version),
// then publish once. The draft collects both platforms: the installers,
// their updater signatures, and `latest.json`, the manifest the app reads.
//
// Options: --notes-file <file> (release notes, Markdown; default: notes
// generated by GitHub from the merged changes), --skip-build (upload what
// is already in target/).
//
// Signing: the updater key made with `pnpm tauri signer generate`. Set
// TAURI_SIGNING_PRIVATE_KEY(_PATH) and TAURI_SIGNING_PRIVATE_KEY_PASSWORD,
// or keep the key at ~/.tauri/flick-updater.key (no password).
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync, spawnSync } from "node:child_process";
import { homedir, tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const option = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};

function fail(message) {
  console.error(`\n✗ ${message}`);
  process.exit(1);
}

function run(cmd, cmdArgs, opts = {}) {
  const r = spawnSync(cmd, cmdArgs, { cwd: root, stdio: "inherit", ...opts });
  if (r.status !== 0) fail(`${cmd} ${cmdArgs.join(" ")} failed`);
}

const out = (cmd, cmdArgs) => execFileSync(cmd, cmdArgs, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();

// ── What is released, and where ─────────────────────────────────────────

const conf = JSON.parse(readFileSync(join(root, "app", "tauri.conf.json"), "utf8"));
const endpoint = conf.plugins?.updater?.endpoints?.[0] ?? "";
const repo = /github\.com\/([^/]+\/[^/]+)\/releases/.exec(endpoint)?.[1];
if (!repo) fail(`the updater endpoint is not a GitHub release: ${endpoint}`);

const cargo = readFileSync(join(root, "Cargo.toml"), "utf8");
const version = /\[workspace\.package\][^[]*?\nversion\s*=\s*"([^"]+)"/.exec(cargo)?.[1];
if (!version) fail("no version in Cargo.toml [workspace.package]");
const tag = `v${version}`;
const assetUrl = (name) => `https://github.com/${repo}/releases/download/${tag}/${encodeURIComponent(name)}`;

try {
  out("gh", ["auth", "status"]);
} catch {
  fail("the GitHub CLI is not signed in: run `gh auth login`");
}

/** `null` when the release does not exist yet. */
function release() {
  try {
    return JSON.parse(out("gh", ["release", "view", tag, "-R", repo, "--json", "isDraft,body,assets"]));
  } catch {
    return null;
  }
}

const work = join(tmpdir(), `flick-release-${version}`);
mkdirSync(work, { recursive: true });

/** The manifest already on the release, or a new one. */
function readManifest() {
  const rel = release();
  if (rel?.assets.some((a) => a.name === "latest.json")) {
    run("gh", ["release", "download", tag, "-R", repo, "-p", "latest.json", "-D", work, "--clobber"], { stdio: "ignore" });
    return JSON.parse(readFileSync(join(work, "latest.json"), "utf8"));
  }
  return { version, notes: "", pub_date: new Date().toISOString(), platforms: {} };
}

function writeManifest(manifest) {
  const file = join(work, "latest.json");
  writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);
  run("gh", ["release", "upload", tag, file, "-R", repo, "--clobber"]);
}

// ── Publish ─────────────────────────────────────────────────────────────

if (flag("--publish")) {
  const rel = release();
  if (!rel) fail(`no release ${tag}: run \`pnpm release\` first`);
  if (!rel.isDraft) fail(`${tag} is already published`);
  const manifest = readManifest();
  const platforms = Object.keys(manifest.platforms);
  for (const os of ["windows", "darwin"]) {
    if (!platforms.some((p) => p.startsWith(`${os}-`))) console.warn(`! no ${os} build in ${tag}: those installs will not be offered this update`);
  }
  // The notes as edited on GitHub; the date of the actual release.
  manifest.notes = rel.body ?? "";
  manifest.pub_date = new Date().toISOString();
  writeManifest(manifest);
  run("gh", ["release", "edit", tag, "-R", repo, "--draft=false", "--latest"]);
  console.log(`\n✓ Flick ${version} is published. Installed copies will offer it at their next launch.`);
  process.exit(0);
}

// ── Build and upload this platform ──────────────────────────────────────

// Windows: NSIS only. It installs per user, so an update installs silently
// without asking for administrator rights; the MSI installs per machine.
const platform = {
  win32: { target: "x86_64-pc-windows-msvc", bundles: ["nsis"] },
  darwin: { target: "aarch64-apple-darwin", bundles: ["app", "dmg"] },
}[process.platform];
if (!platform) fail(`releases are built on Windows and macOS, not ${process.platform}`);

const existing = release();
if (existing && !existing.isDraft) fail(`${tag} is already published: raise the version in Cargo.toml first`);

const head = out("git", ["rev-parse", "HEAD"]);
if (out("git", ["status", "--porcelain", "--untracked-files=no"])) console.warn("! uncommitted changes: the release is built from the working tree");
if (!out("git", ["branch", "-r", "--contains", head])) fail("this commit is not pushed: GitHub tags the release on it, push first");

if (!process.env.TAURI_SIGNING_PRIVATE_KEY && !process.env.TAURI_SIGNING_PRIVATE_KEY_PATH) {
  const key = join(homedir(), ".tauri", "flick-updater.key");
  if (!existsSync(key)) fail(`no updater signing key: set TAURI_SIGNING_PRIVATE_KEY, or put the key at ${key}`);
  process.env.TAURI_SIGNING_PRIVATE_KEY = readFileSync(key, "utf8");
}
process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD ??= "";

const bundle = join(root, "target", platform.target, "release", "bundle");
if (!flag("--skip-build")) {
  // Updater artifacts only here, so everyday builds need no key.
  const extra = join(work, "updater.conf.json");
  writeFileSync(extra, JSON.stringify({ bundle: { createUpdaterArtifacts: true, targets: platform.bundles } }));
  run(process.execPath, ["tools/ensure-libmpv.mjs"]);
  // The CLI's own entry point: no shell, so no quoting to get wrong.
  run(process.execPath, [join(root, "node_modules", "@tauri-apps", "cli", "tauri.js"), "build", "--target", platform.target, "--config", extra]);
}

/** Files in `bundle/<dir>` whose name ends with `suffix` and carries this version (the .app tarball does not). */
function find(dir, suffix, versioned = true) {
  const path = join(bundle, dir);
  const hits = existsSync(path) ? readdirSync(path).filter((f) => f.endsWith(suffix) && (!versioned || f.includes(`_${version}_`))) : [];
  if (hits.length !== 1) fail(`expected one ${suffix} for ${version} in ${path}, found ${hits.length}`);
  return join(path, hits[0]);
}

/** The package and its signature, uploaded under `name`. */
function signed(file, name = basename(file)) {
  const sig = `${file}.sig`;
  if (!existsSync(sig)) fail(`${basename(file)} is not signed (no .sig): was the build made by this script?`);
  const copy = join(work, name);
  copyFileSync(file, copy);
  return { file: copy, url: assetUrl(name), signature: readFileSync(sig, "utf8").trim() };
}

const uploads = [];
const entries = {};
if (process.platform === "win32") {
  const nsis = signed(find("nsis", "-setup.exe"));
  uploads.push(nsis.file);
  // The updater looks for `<os>-<arch>-<installer>`, then `<os>-<arch>`.
  entries["windows-x86_64-nsis"] = { url: nsis.url, signature: nsis.signature };
  entries["windows-x86_64"] = entries["windows-x86_64-nsis"];
} else {
  const app = signed(find("macos", ".app.tar.gz", false), `Flick_${version}_aarch64.app.tar.gz`);
  const dmg = find("dmg", ".dmg");
  uploads.push(app.file, dmg);
  // Apple silicon only: Intel Macs are not offered this build.
  entries["darwin-aarch64-app"] = { url: app.url, signature: app.signature };
  entries["darwin-aarch64"] = { url: app.url, signature: app.signature };
}

if (!existing) {
  const notes = option("--notes-file");
  run("gh", [
    "release", "create", tag, "-R", repo, "--draft", "--target", head, "--title", `Flick ${version}`,
    ...(notes ? ["--notes-file", notes] : ["--generate-notes"]),
  ]);
}
run("gh", ["release", "upload", tag, ...uploads, "-R", repo, "--clobber"]);

const manifest = readManifest();
manifest.version = version;
manifest.notes = release()?.body ?? manifest.notes;
Object.assign(manifest.platforms, entries);
writeManifest(manifest);

console.log(`\n✓ ${process.platform === "win32" ? "Windows" : "macOS"} build uploaded to the draft ${tag} (${Object.keys(manifest.platforms).length} updater targets).`);
console.log("  Build the other platform with `pnpm release`, review the notes on GitHub, then `pnpm release:publish`.");
