// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaItem } from "./MediaItem";

/**
 * Previous/next items around an episode, for autoplay and player buttons.
 */
export type Adjacent = { previous: MediaItem | null, next: MediaItem | null, };
