// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminServerInfo = { name: string, version: string, os: string | null, updateAvailable: boolean | null, transcodeHwAccel: string | null, 
/**
 * Arbitrary provider-specific facts shown as a key/value list.
 */
extra: Array<[string, string]>, };
