// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminTask = { id: string, name: string, category: string | null, state: string, progress: number | null, lastResult: string | null, };
