// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenterChoice } from "./PresenterChoice";

export type AdvancedSettings = { 
/**
 * Explicit libmpv path (otherwise bundled/system).
 */
libmpvPath: string | null, presenter: PresenterChoice, 
/**
 * Extra raw mpv options, applied last. Power users only.
 */
extraMpvOptions: Array<[string, string]>, logLevel: string, showDebugOverlay: boolean, };
