// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerIssue } from "./ServerIssue";

export type Aggregated<T> = { data: T, 
/**
 * Servers that failed or timed out; the UI shows a discreet notice.
 */
issues: Array<ServerIssue>, };
