// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Density } from "./Density";

export type AppearanceSettings = { 
/**
 * Accent colour as `#rrggbb`.
 */
accent: string, 
/**
 * 0 = no motion (also honoured from the OS "reduce motion"), 1 = full.
 */
animationIntensity: number, 
/**
 * Strength of the adaptive artwork background, 0..=1.
 */
backgroundIntensity: number, blur: boolean, density: Density, };
