// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioConnection } from "./AudioConnection";
import type { PassthroughProbe } from "./PassthroughProbe";

export type AudioDevice = { 
/**
 * OS endpoint id.
 */
id: string, 
/**
 * Name libmpv uses for `--audio-device` (e.g. `wasapi/{guid}`).
 */
mpvName: string | null, name: string, connection: AudioConnection, 
/**
 * Channels of the OS mixer format (what shared-mode PCM output gets).
 */
channels: number, channelLayout: string | null, sampleRate: number | null, passthrough: PassthroughProbe, };
