// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitstreamFormat } from "./BitstreamFormat";

export type AudioOutputPlan = { "mode": "bitstream", format: BitstreamFormat, device: string, reencoded: boolean, } | { "mode": "pcm", sourceChannels: number, outputChannels: number, downmix: boolean, spatialLost: boolean, } | { "mode": "serverDetermined" } | { "mode": "none" };
