// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitstreamFormat } from "./BitstreamFormat";
import type { ChannelOverride } from "./ChannelOverride";
import type { Normalization } from "./Normalization";

export type AudioSettings = { 
/**
 * OS endpoint id; `None` = OS default device.
 */
device: string | null, channels: ChannelOverride, 
/**
 * Master switch for bitstreaming.
 */
passthrough: boolean, 
/**
 * Formats the user allows to bitstream (intersected with the probe).
 */
passthroughFormats: Array<BitstreamFormat>, 
/**
 * WASAPI exclusive mode for PCM too (bit-perfect, blocks other apps).
 */
exclusive: boolean, normalization: Normalization, 
/**
 * Encode multichannel PCM to AC3 for S/PDIF receivers (lossy).
 */
ac3Reencode: boolean, volume: number, 
/**
 * Amplify beyond 100 % (quiet mixes, laptop speakers). Decoded audio only:
 * bitstreamed tracks reach the receiver untouched.
 */
volumeBoost: boolean, 
/**
 * Gain while boosting, in percent of the original level (110..=300).
 */
volumeBoostPercent: number, };
