// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioCodec = "aac" | "ac3" | "eac3" | "dts" | "dtshd" | "truehd" | "flac" | "alac" | "opus" | "vorbis" | "mp3" | "pcm" | { "other": string };
