// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioConnection = "hdmi" | "displayPort" | "spdif" | "usb" | "bluetooth" | "analog" | "builtin" | "virtual" | "unknown";
