// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCodec } from "./AudioCodec";
import type { SpatialAudio } from "./SpatialAudio";

export type AudioStream = { index: number, codec: AudioCodec, profile: string | null, channels: number, channelLayout: string | null, sampleRate: number | null, bitrate: number | null, spatial: SpatialAudio | null, language: string | null, title: string | null, isDefault: boolean, isCommentary: boolean, };
