// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDevice } from "./AudioDevice";

export type AudioCapabilities = { devices: Array<AudioDevice>, 
/**
 * Id of the OS default render device.
 */
defaultDevice: string | null, };
