// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compressed formats that can be sent untouched ("bitstreamed") over
 * S/PDIF or HDMI. Names match mpv's `--audio-spdif` values.
 */
export type BitstreamFormat = "ac3" | "eac3" | "dts" | "dts-hd" | "truehd";
