// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCapabilities } from "./AudioCapabilities";
import type { DisplayCapabilities } from "./DisplayCapabilities";
import type { SystemCapabilities } from "./SystemCapabilities";
import type { VideoCapabilities } from "./VideoCapabilities";

export type CapabilityReport = { system: SystemCapabilities, displays: Array<DisplayCapabilities>, audio: AudioCapabilities, video: VideoCapabilities, probedAt: string, 
/**
 * Human-readable caveats discovered while probing.
 */
notes: Array<string>, };
