// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastDevice } from "./CastDevice";
import type { CastState } from "./CastState";

/**
 * What the receiver reports.
 */
export type CastStatus = { device: CastDevice | null, state: CastState, positionMs: number, durationMs: number | null, 
/**
 * 0..=1, when the receiver tells.
 */
volume: number | null, error: string | null, };
