// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastKind } from "./CastKind";

/**
 * A receiver found on the network.
 */
export type CastDevice = { id: string, name: string, kind: CastKind, model: string | null, host: string, port: number, };
