// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { id: number, sender_id: string, sender_name: string, text: string, 
/**
 * Milliseconds since the Unix epoch.
 */
timestamp: number, };
