// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCodec } from "./AudioCodec";
import type { SubtitleFormat } from "./SubtitleFormat";
import type { VideoCodec } from "./VideoCodec";

/**
 * What the client declares it can decode *locally*. Sent to the server so it
 * never transcodes merely because it does not know the client.
 */
export type ClientProfile = { name: string, 
/**
 * `None` = unlimited (LAN). Remote limits are applied by the server.
 */
maxBitrate: number | null, videoCodecs: Array<VideoCodec>, audioCodecs: Array<AudioCodec>, 
/**
 * Containers the demuxer handles (FFmpeg: effectively all).
 */
containers: Array<string>, subtitleFormats: Array<SubtitleFormat>, 
/**
 * Maximum decodable resolution (bounded by HW decoder limits when SW
 * decode would be too slow; see decision engine).
 */
maxWidth: number, maxHeight: number, maxAudioChannels: number, };
