// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomState } from "./RoomState";
import type { UserMessage } from "./UserMessage";

/**
 * What the UI layer receives.
 */
export type ClientEvent = { "type": "state", room: RoomState, } | { "type": "notice", message: UserMessage, } | { "type": "mediaUnavailable", title: string | null, } | { "type": "left", reason: string | null, };
