// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionState = "disconnected" | "connecting" | "connected" | "reconnecting" | "authentication_failed" | "unavailable" | "error";
