// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControllerSettings = { enabled: boolean, deadzone: number, 
/**
 * Swap A/B (Nintendo layout).
 */
swapConfirm: boolean, };
