// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";
import type { ItemRef } from "./ItemRef";
import type { PersonRole } from "./PersonRole";

export type Credit = { person: ItemRef, name: string, role: PersonRole, 
/**
 * Character name for actors, job title otherwise.
 */
character: string | null, image: ImageRef | null, };
