// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionState } from "./ConnectionState";

export type DebugInfo = { connection: ConnectionState, roomId: string, participantId: string, rttMs: number | null, canonicalPosition: number | null, localPosition: number | null, driftMs: number, correctionRate: number, sequence: number, lastServerEvent: string, };
