// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasonSeverity } from "./ReasonSeverity";

/**
 * One explainable step of the decision, shown in diagnostics.
 */
export type DecisionReason = { code: string, severity: ReasonSeverity, message: string, };
