// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCodec } from "./AudioCodec";
import type { VideoCodec } from "./VideoCodec";

/**
 * How bytes travel from the server.
 */
export type DeliveryRequest = { "type": "direct" } | { "type": "remux", container: string, } | { "type": "transcode", video: VideoCodec | null, audio: AudioCodec | null, maxBitrate: number | null, maxWidth: number | null, audioChannels: number | null, 
/**
 * Burn this subtitle stream into the video (only when unavoidable).
 */
burnSubtitle: number | null, };
