// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HdrState } from "./HdrState";
import type { Rect } from "./Rect";

export type DisplayCapabilities = { 
/**
 * OS identifier (`\\.\DISPLAY1`, CGDirectDisplayID, output name).
 */
id: string, name: string, isPrimary: boolean, width: number, height: number, refreshHz: number | null, bitsPerColor: number | null, hdr: HdrState, 
/**
 * Desktop rectangle in virtual-screen coordinates (to map a window to a display).
 */
bounds: Rect, };
