// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DolbyVisionCompat } from "./DolbyVisionCompat";

export type DynamicRange = { "kind": "sdr" } | { "kind": "hdr10" } | { "kind": "hdr10-plus" } | { "kind": "hlg" } | { "kind": "dolby-vision", profile: number | null, compat: DolbyVisionCompat, 
/**
 * Profile 7 enhancement layer present (FEL/MEL).
 */
enhancementLayer: boolean, } | { "kind": "unknown" };
