// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";

/**
 * Episode/season placement inside a series.
 */
export type EpisodeInfo = { series: ItemRef | null, seriesTitle: string | null, season: ItemRef | null, seasonNumber: number | null, episodeNumber: number | null, episodeNumberEnd: number | null, };
