// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * External database identifiers; used to merge the same title found on
 * several servers into one card.
 */
export type ExternalIds = { imdb: string | null, tmdb: string | null, tvdb: string | null, };
