// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Watch together. FlickSync is optional: with no invitation link saved the
 * feature is hidden and the rest of Flick is unaffected. The link (address +
 * key) lives in the OS keychain, never here.
 */
export type FlickSyncSettings = { enabled: boolean,
/**
 * Shown to the other participants; defaults to the profile or account name.
 */
displayName: string | null, };
