// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Watch together. FlickSync is optional: with nothing configured the
 * feature is hidden and the rest of Flick is unaffected.
 */
export type FlickSyncSettings = { enabled: boolean, 
/**
 * The Flick Server, which says where FlickSync is and issues its tokens.
 */
flickServerUrl: string | null, 
/**
 * Manual FlickSync address, for a self-hosted service without a Flick Server.
 * The signing key it needs lives in the OS keychain, never here.
 */
syncUrl: string | null, 
/**
 * Shown to the other participants; defaults to the profile or account name.
 */
displayName: string | null, };
