// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralSettings = { 
/**
 * BCP-47 UI language; `None` follows the OS.
 */
language: string | null, startInMaxiFrame: boolean, 
/**
 * Look for a new release at launch and offer to install it.
 */
checkForUpdates: boolean, };
