// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { SortBy } from "./SortBy";
import type { SortOrder } from "./SortOrder";

/**
 * Titles of one kind in one genre, across every library of a server. Paged
 * per server: each server answers `start`/`limit` on its own.
 */
export type GenreQuery = {
/**
 * `Movie` or `Series`: they are browsed separately.
 */
kind: ItemKind, genre: string, sort: SortBy, order: SortOrder, start: number, limit: number, };
