// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuVendor } from "./GpuVendor";

export type GpuInfo = { name: string, vendor: GpuVendor, dedicatedMemoryBytes: number | null, driverVersion: string | null, };
