// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCodec } from "./VideoCodec";

export type HardwareDecoder = { codec: VideoCodec, 
/**
 * Driver profile name, e.g. `HEVC Main10`.
 */
profile: string, maxBitDepth: number, 
/**
 * Decoding API (`d3d11va`, `videotoolbox`, `vaapi`, `nvdec`, `vulkan`).
 */
api: string, maxWidth: number | null, maxHeight: number | null, };
