// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HDR state of one display *as the OS currently drives it*.
 */
export type HdrState = { "state": "unsupported" } | { "state": "supportedButOff" } | { "state": "active", maxLuminance: number | null, minLuminance: number | null, maxFullFrameLuminance: number | null, } | { "state": "unknown", reason: string, };
