// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeRowKind } from "./HomeRowKind";
import type { MediaItem } from "./MediaItem";

export type HomeRow = { kind: HomeRowKind, title: string, items: Array<MediaItem>, };
