// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";

/**
 * Semantic home rows. Providers only return the rows they can back with real
 * data; the aggregator merges rows of the same kind across servers.
 */
export type HomeRowKind = { "type": "continueWatching" } | { "type": "nextUp" } | { "type": "recentlyAdded", library: ItemRef | null, } | { "type": "recommended" } | { "type": "popular" } | { "type": "collections" } | { "type": "playlists" } | { "type": "liveTvOnNow" } | { "type": "custom", key: string, };
