// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Artwork role. Providers map their own naming onto these.
 */
export type ImageKind = "poster" | "backdrop" | "thumb" | "logo" | "banner";
