// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";

export type ImageSet = { poster: ImageRef | null, backdrop: ImageRef | null, thumb: ImageRef | null, logo: ImageRef | null, banner: ImageRef | null, };
