// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageKind } from "./ImageKind";
import type { ItemRef } from "./ItemRef";

/**
 * Opaque handle to a server-side image. The UI requests it through the
 * `oneshot-img://` protocol with a size hint; the Rust side resolves it to an
 * authenticated URL, so credentials never reach the WebView.
 */
export type ImageRef = { item: ItemRef, kind: ImageKind, 
/**
 * Provider-specific locator (Jellyfin image tag, Plex relative path).
 */
tag: string, 
/**
 * Optional blurhash (Jellyfin) for instant low-res placeholders.
 */
blurhash: string | null, };
