// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Size buckets used everywhere artwork is requested: bounded set so the
 * on-disk cache has a high hit rate and the server can cache its resizes.
 */
export type ImageSize = "tiny" | "card" | "large" | "hero" | "original";
