// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";

export type ItemFilter = { genres: Array<string>, years: Array<number>, person: ItemRef | null, unplayedOnly: boolean, favoritesOnly: boolean, };
