// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemKind = "movie" | "series" | "season" | "episode" | "collection" | "playlist" | "person" | "folder" | "musicVideo" | "video" | "tvChannel" | "other";
