// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Globally unique reference to an item: which server connection + the
 * provider's own key (Jellyfin GUID, Plex ratingKey).
 *
 * Serialized as `"<server-uuid>:<provider-key>"` so the UI can treat it as an
 * opaque string key.
 */
export type ItemRef = string;
