// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemFilter } from "./ItemFilter";
import type { ItemKind } from "./ItemKind";
import type { ItemRef } from "./ItemRef";
import type { SortBy } from "./SortBy";
import type { SortOrder } from "./SortOrder";

/**
 * Paged catalogue query. `parent` is a library, collection, playlist, etc.
 */
export type ItemQuery = { parent: ItemRef | null, kinds: Array<ItemKind>, filter: ItemFilter, sort: SortBy, order: SortOrder, start: number, limit: number, };
