// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";

/**
 * A title of the person's TMDB filmography.
 */
export type KnownFor = { 
/**
 * `Movie` or `Series`.
 */
kind: ItemKind, title: string, year: number | null, 
/**
 * Character played, or job for crew.
 */
role: string | null, 
/**
 * TMDB poster file (`/abc.jpg`).
 */
poster: string | null, tmdbId: string, voteCount: number, };
