// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryKind = "movies" | "shows" | "music" | "photos" | "musicVideos" | "homeVideos" | "mixed" | "liveTv" | "other";
