// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";
import type { ItemRef } from "./ItemRef";
import type { LibraryKind } from "./LibraryKind";

export type Library = { id: ItemRef, name: string, kind: LibraryKind, itemCount: number | null, image: ImageRef | null, };
