// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What mpv is *actually* doing (vs. what the decision planned).
 */
export type LiveStats = { hwdec: string | null, videoParams: unknown, videoTarget: unknown, audioParams: unknown, audioOut: unknown, currentAo: string | null, containerFps: number | null, displayFps: number | null, droppedFrames: number | null, decoderDroppedFrames: number | null, avsync: number | null, videoBitrate: number | null, audioBitrate: number | null, };
