// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkerKind } from "./MarkerKind";

/**
 * Intro/credits/recap markers used by "Skip intro".
 */
export type Marker = { kind: MarkerKind, startMs: number, endMs: number, };
