// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioStream } from "./AudioStream";
import type { SubtitleStream } from "./SubtitleStream";
import type { VideoStream } from "./VideoStream";

/**
 * One playable version of an item (a file, or one "version" of a movie).
 */
export type MediaSource = { id: string, name: string | null, container: string | null, sizeBytes: number | null, bitrate: number | null, durationMs: number | null, video: Array<VideoStream>, audio: Array<AudioStream>, subtitles: Array<SubtitleStream>, };
