// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Credit } from "./Credit";
import type { EpisodeInfo } from "./EpisodeInfo";
import type { ExternalIds } from "./ExternalIds";
import type { ImageSet } from "./ImageSet";
import type { ItemKind } from "./ItemKind";
import type { ItemRef } from "./ItemRef";
import type { MediaSource } from "./MediaSource";
import type { UserState } from "./UserState";

export type MediaItem = { id: ItemRef, kind: ItemKind, title: string, sortTitle: string | null, originalTitle: string | null, tagline: string | null, overview: string | null, year: number | null, premiereDate: string | null, runtimeMs: number | null, officialRating: string | null, communityRating: number | null, criticRating: number | null, genres: Array<string>, studios: Array<string>, credits: Array<Credit>, images: ImageSet, user: UserState, episode: EpisodeInfo | null, externalIds: ExternalIds, childCount: number | null, addedAt: string | null, 
/**
 * Technical sources; only populated on detail fetches.
 */
sources: Array<MediaSource>, 
/**
 * The same title on other servers (merged by external ids).
 */
alternates?: Array<ItemRef>, };
