// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaType } from "./MediaType";
import type { Provider } from "./Provider";

/**
 * Identity of a title. FlickSync only carries it; every client resolves it
 * through its own Jellyfin/Plex connection.
 */
export type MediaRef = { provider: Provider, server_id: string, media_id: string, media_type: MediaType, season_id?: string | null, episode_id?: string | null, 
/**
 * Display only.
 */
title?: string | null, duration_secs?: number | null, };
