// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpFamily } from "./IpFamily";

export type NetworkSettings = { concurrentRequests: number, timeoutSecs: number, 
/**
 * Demuxer read-ahead buffer, in MiB.
 */
bufferMib: number, proxy: string | null, ipFamily: IpFamily, 
/**
 * Accept invalid/self-signed TLS certificates for *all* servers.
 * Explicit opt-in for LAN servers with self-signed certificates; the UI
 * shows a permanent warning while enabled.
 */
allowInvalidCertificates: boolean, };
