// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

export type Participant = { participant_id: string, display_name: string, presence: Presence, is_host: boolean, };
