// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitstreamFormat } from "./BitstreamFormat";

/**
 * Result of probing a device for compressed passthrough.
 */
export type PassthroughProbe = { "state": "probed", formats: Array<BitstreamFormat>, } | { "state": "notSupportedByPlatform", reason: string, } | { "state": "notProbed", reason: string, };
