// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";

export type PersonPhoto = { "kind": "server", image: ImageRef, } | { "kind": "tmdb", path: string, };
