// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownFor } from "./KnownFor";
import type { PersonPhoto } from "./PersonPhoto";
import type { TmdbUse } from "./TmdbUse";

export type PersonDetails = { name: string, department: string | null, biography: string | null, birth: string | null, death: string | null, birthplace: string | null, photo: PersonPhoto | null, 
/**
 * TMDB filmography, most voted first (the UI removes titles on the servers).
 */
knownFor: Array<KnownFor>, tmdb: TmdbUse, };
