// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";
import type { ItemRef } from "./ItemRef";
import type { Phase } from "./Phase";
import type { PlaybackDecision } from "./PlaybackDecision";
import type { PresenterKind } from "./PresenterKind";
import type { Track } from "./Track";

export type PlayerSnapshot = { phase: Phase, item: ItemRef | null, positionMs: number, durationMs: number | null, bufferedMs: number | null, volume: number, muted: boolean, tracks: Array<Track>, chapters: Array<Chapter>, decision: PlaybackDecision | null, presenter: PresenterKind | null, 
/**
 * Effective mpv properties applied for this file (Debug panel).
 */
appliedOptions: Array<[string, string]>, error: string | null, };
