// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { SourceOffer } from "./SourceOffer";

export type PlaybackInfo = { item: ItemRef, offers: Array<SourceOffer>, 
/**
 * Session id the server wants echoed back in reports (Jellyfin).
 */
playSessionId: string | null, };
