// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";
import type { ItemRef } from "./ItemRef";
import type { Phase } from "./Phase";
import type { PlaybackDecision } from "./PlaybackDecision";
import type { Track } from "./Track";

export type PlayerEvent = { "type": "state", phase: Phase, positionMs: number, durationMs: number | null, bufferedMs: number | null, volume: number, muted: boolean, } | { "type": "tracks", tracks: Array<Track>, } | { "type": "chapters", chapters: Array<Chapter>, } | { "type": "decision", decision: PlaybackDecision, } | { "type": "ended", item: ItemRef | null, natural: boolean, } | { "type": "error", message: string, };
