// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioOutputPlan } from "./AudioOutputPlan";
import type { DecisionReason } from "./DecisionReason";
import type { DeliveryRequest } from "./DeliveryRequest";
import type { StrategyLabel } from "./StrategyLabel";
import type { SubtitlePlan } from "./SubtitlePlan";
import type { VideoOutputPlan } from "./VideoOutputPlan";

export type PlaybackDecision = { label: StrategyLabel, sourceId: string, delivery: DeliveryRequest, videoStream: number | null, audioStream: number | null, video: VideoOutputPlan, audio: AudioOutputPlan, subtitles: SubtitlePlan, 
/**
 * Whether video decoding is expected to be hardware-accelerated.
 */
hardwareDecode: boolean | null, reasons: Array<DecisionReason>, };
