// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryKind } from "./DeliveryKind";
import type { ItemRef } from "./ItemRef";
import type { PlaybackState } from "./PlaybackState";
import type { ReportKind } from "./ReportKind";

/**
 * Progress report sent to the server (resume point, "now playing", scrobble).
 */
export type PlaybackReport = { kind: ReportKind, item: ItemRef, sourceId: string, playSessionId: string | null, state: PlaybackState, positionMs: number, durationMs: number | null, delivery: DeliveryKind, audioIndex: number | null, subtitleIndex: number | null, volume: number, muted: boolean, };
