// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { TrackRequest } from "./TrackRequest";

export type PlayRequest = { item: ItemRef | null, 
/**
 * Specific version; `None` = first offer.
 */
sourceId: string | null, startMs: number | null, audio: TrackRequest, subtitle: TrackRequest, };
