// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResumeBehavior } from "./ResumeBehavior";
import type { SkipMode } from "./SkipMode";

export type PlaybackSettings = { 
/**
 * Upper bound for streaming bitrate (bits/s). `None` = original quality.
 */
maxBitrate: number | null, 
/**
 * Allow the server to remux when it refuses direct play.
 */
allowDirectStream: boolean, 
/**
 * Allow server transcoding at all. When false, unplayable = error.
 */
allowTranscode: boolean, 
/**
 * Prefer a server transcode over CPU decoding when the GPU cannot decode
 * a source at or above this height (e.g. 2160 on a weak laptop).
 */
transcodeWithoutHwdecMinHeight: number | null, resume: ResumeBehavior, autoplayNext: boolean, autoplayCountdownSecs: number, skipIntro: SkipMode, skipCredits: SkipMode, 
/**
 * Progress report interval to the server.
 */
reportIntervalSecs: number, preferredAudioLanguages: Array<string>, };
