// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayState } from "./PlayState";

export type PlaybackView = { state: PlayState, position: number, rate: number, sequence: number, };
