// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackType } from "./TrackType";

export type PlayerCommand = { "type": "setPause", paused: boolean, } | { "type": "togglePause" } | { "type": "seekAbsolute", ms: number, } | { "type": "seekRelative", ms: number, } | { "type": "setVolume", volume: number, } | { "type": "setMute", muted: boolean, } | { "type": "selectTrack", kind: TrackType, mpvId: number | null, } | { "type": "setSpeed", speed: number, } | { "type": "setSubtitleDelay", ms: number, } | { "type": "setAudioDelay", ms: number, } | { "type": "stop" };
