// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrivacySettings = { 
/**
 * Report playback progress to servers (disabling breaks resume sync).
 */
reportProgress: boolean, };
