// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountState } from "./AccountState";
import type { ProviderKind } from "./ProviderKind";
import type { ServerId } from "./ServerId";

export type ProfileAccount = { kind: ProviderKind, serverName: string, userName: string, state: AccountState, connection: ServerId | null, 
/**
 * Where a pending Jellyfin account signs in.
 */
baseUrl: string, needsPassword: boolean, 
/**
 * A Plex Home member protected by a Plex PIN.
 */
plexPin: boolean, };
