// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where profiles come from.
 */
export type ProfileMode = "serverUsers" | "local" | "linked";
