// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileAccount } from "./ProfileAccount";
import type { ProfileId } from "./ProfileId";

export type ProfileCard = { id: ProfileId, name: string, color: string, 
/**
 * Changes with the picture; `None` = initials.
 */
avatarKey: string | null, 
/**
 * Protected by a Flick PIN.
 */
locked: boolean, hidden: boolean, 
/**
 * Other people were merged into this one by hand (can be undone).
 */
merged: boolean, accounts: Array<ProfileAccount>, };
