// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileCard } from "./ProfileCard";
import type { ProfileId } from "./ProfileId";
import type { ProfileMode } from "./ProfileMode";

export type ProfilesState = { enabled: boolean, mode: ProfileMode, askOnStartup: boolean, active: ProfileId | null, profiles: Array<ProfileCard>, 
/**
 * At least one profile has a PIN (mode changes then need one).
 */
anyLocked: boolean, };
