// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ConnectionState } from "./ConnectionState";
import type { ControlMode } from "./ControlMode";
import type { MediaRef } from "./MediaRef";
import type { Participant } from "./Participant";
import type { PlaybackView } from "./PlaybackView";

export type RoomState = { roomId: string, shareCode: string, hostId: string, 
/**
 * Our own participant id.
 */
you: string, participants: Array<Participant>, media: MediaRef | null, playback: PlaybackView | null, controlMode: ControlMode, chatEnabled: boolean, connection: ConnectionState, chat: Array<ChatMessage>, 
/**
 * Why the room ended, once it did (`host_closed`, `expired`, …).
 */
closedReason: string | null, };
