// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-side view of a source: what the server allows for this user/network.
 */
export type ServerPolicy = { directPlayAllowed: boolean, directStreamAllowed: boolean, transcodeAllowed: boolean, 
/**
 * Raw reasons reported by the server when it would not direct play.
 */
serverReasons: Array<string>, };
