// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Library } from "./Library";
import type { ServerDescriptor } from "./ServerDescriptor";

export type ServerLibraries = { server: ServerDescriptor, libraries: Array<Library>, };
