// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Locally-assigned identifier of a configured server connection.
 *
 * It is *not* the server's own ID: the same physical server may be added
 * twice with different accounts, and each connection must stay distinct.
 */
export type ServerId = string;
