// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection health, surfaced in the Servers screen and diagnostics.
 */
export type ServerStatus = { "state": "online", latencyMs: number, url: string, } | { "state": "unauthorized" } | { "state": "unreachable", error: string, };
