// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { ServerId } from "./ServerId";
import type { UserProfile } from "./UserProfile";

/**
 * A configured server connection, as persisted (without secrets: tokens
 * live in the OS keychain, keyed by `id`).
 */
export type ServerDescriptor = { id: ServerId, kind: ProviderKind, 
/**
 * Display name reported by the server (user-renamable).
 */
name: string, 
/**
 * Server's own unique id (Jellyfin `Id`, Plex `machineIdentifier`).
 */
remoteId: string, baseUrl: string, 
/**
 * Alternative addresses (Plex exposes local, remote and relay ones).
 */
alternateUrls: Array<string>, version: string | null, user: UserProfile, };
