// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { AudioSettings } from "./AudioSettings";
import type { CacheSettings } from "./CacheSettings";
import type { ControllerSettings } from "./ControllerSettings";
import type { FlickSyncSettings } from "./FlickSyncSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { NetworkSettings } from "./NetworkSettings";
import type { NotificationSettings } from "./NotificationSettings";
import type { PlaybackSettings } from "./PlaybackSettings";
import type { PrivacySettings } from "./PrivacySettings";
import type { SubtitleSettings } from "./SubtitleSettings";
import type { VideoSettings } from "./VideoSettings";

export type Settings = { general: GeneralSettings, appearance: AppearanceSettings, playback: PlaybackSettings, audio: AudioSettings, video: VideoSettings, subtitles: SubtitleSettings, network: NetworkSettings, cache: CacheSettings, controller: ControllerSettings, notifications: NotificationSettings, privacy: PrivacySettings, flicksync: FlickSyncSettings, advanced: AdvancedSettings, };
