// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSource } from "./MediaSource";
import type { ServerPolicy } from "./ServerPolicy";

export type SourceOffer = { source: MediaSource, policy: ServerPolicy, };
