// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Object-based / immersive audio carried inside a codec.
 */
export type SpatialAudio = "dolby-atmos" | "dts-x";
