// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing summary of the strategy.
 */
export type StrategyLabel = "directPlay" | "directStream" | "localDecode" | "serverTranscode";
