// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryRequest } from "./DeliveryRequest";
import type { ItemRef } from "./ItemRef";

export type StreamRequest = { item: ItemRef, sourceId: string, playSessionId: string | null, delivery: DeliveryRequest, audioIndex: number | null, subtitleIndex: number | null, startMs: number, };
