// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleMode } from "./SubtitleMode";

export type SubtitleSettings = { mode: SubtitleMode, languages: Array<string>, 
/**
 * System font family; empty = the platform's default subtitle font.
 * Replaces the former `font` field, whose default ("Inter") is only
 * bundled with the UI, not installed where libass looks for fonts.
 */
fontFamily: string, bold: boolean, 
/**
 * Relative size, 1.0 = default.
 */
scale: number, color: string, background: string, backgroundOpacity: number, outline: number, 
/**
 * Vertical position, 100 = bottom.
 */
position: number, 
/**
 * Override ASS styling with the settings above.
 */
overrideAss: boolean, };
