// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleFormat } from "./SubtitleFormat";

export type SubtitleStream = { index: number, format: SubtitleFormat, language: string | null, title: string | null, forced: boolean, hearingImpaired: boolean, isDefault: boolean, 
/**
 * Sidecar file served separately by the server (not muxed in the container).
 */
external: boolean, };
