// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitlePlan = { "mode": "none" } | { "mode": "local", index: number, external: boolean, } | { "mode": "burnIn", index: number, };
