// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";
import type { OsKind } from "./OsKind";

export type SystemCapabilities = { os: OsKind, osVersion: string, arch: string, cpuModel: string | null, cpuThreads: number, memoryBytes: number | null, gpus: Array<GpuInfo>, };
