// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether TMDB contributed to the page, and if not, why.
 */
export type TmdbUse = "used" | "noKey" | "notFound" | "unavailable";
