// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackType } from "./TrackType";

/**
 * A track as mpv sees it, enriched for the UI.
 */
export type Track = { kind: TrackType, mpvId: number, 
/**
 * Container stream index (provider numbering), if embedded.
 */
streamIndex: number | null, externalUrl: string | null, title: string | null, language: string | null, codec: string | null, channels: number | null, default: boolean, forced: boolean, selected: boolean, width: number | null, height: number | null, };
