// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackRequest = { "type": "auto" } | { "type": "off" } | { "type": "index", "index": number };
