// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfile = { id: string, name: string, avatar: string | null, 
/**
 * Server-side administrator. Only used to *show* admin entry points; the
 * server still enforces every permission.
 */
isAdmin: boolean, };
