// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable codes the UI maps to localized text.
 */
export type UserMessage = "only_host_can_choose_media" | "control_denied" | "room_not_found" | "room_full" | "room_closed" | "invalid_media" | "session_expired" | "slow_down" | "chat_disabled" | "incompatible_version" | "unavailable" | "media_unavailable" | "not_configured" | "generic";
