// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-user state of an item, owned by the server.
 */
export type UserState = { played: boolean, playCount: number, positionMs: number, favorite: boolean, lastPlayed: string | null, 
/**
 * Unplayed children (series/season).
 */
unplayedCount: number | null, };
