// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoOutputPlan = { "mode": "sdr" } | { "mode": "hdrPassthrough", format: string, } | { "mode": "toneMapToSdr", reason: string, } | { "mode": "dolbyVisionReshape", output: string, } | { "mode": "serverDetermined" };
