// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicRange } from "./DynamicRange";
import type { VideoCodec } from "./VideoCodec";

export type VideoStream = { index: number, codec: VideoCodec, profile: string | null, level: number | null, width: number, height: number, bitDepth: number | null, frameRate: number | null, bitrate: number | null, range: DynamicRange, interlaced: boolean, title: string | null, isDefault: boolean, };
