// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardwareDecoder } from "./HardwareDecoder";
import type { VideoCodec } from "./VideoCodec";

export type VideoCapabilities = { 
/**
 * Hardware decode profiles exposed by the GPU driver.
 */
hardwareDecoders: Array<HardwareDecoder>, 
/**
 * Whether hardware decode enumeration actually ran (vs. unknown).
 */
hardwareProbeOk: boolean, 
/**
 * Decoders available in the playback engine (software, FFmpeg).
 */
softwareCodecs: Array<VideoCodec>, };
