// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deinterlace } from "./Deinterlace";
import type { FrameSync } from "./FrameSync";
import type { HardwareDecoding } from "./HardwareDecoding";
import type { HdrMode } from "./HdrMode";
import type { ToneMapping } from "./ToneMapping";

export type VideoSettings = { hardwareDecoding: HardwareDecoding, hdr: HdrMode, toneMapping: ToneMapping, 
/**
 * Per-scene peak detection for tone mapping (costs GPU time).
 */
hdrPeakDetection: boolean, deinterlace: Deinterlace, frameSync: FrameSync, 
/**
 * Motion interpolation (requires display-resample).
 */
interpolation: boolean, };
