// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Video rectangle in physical pixels, relative to the host client area.
 */
export type Viewport = { x: number, y: number, width: number, height: number, };
